#include "dwarf_support_matrix.hpp"

namespace dwarf {

const std::vector<SupportMatrixRow>& getSupportMatrixRows() {
    static const std::vector<SupportMatrixRow> kRows = {
        {"forms", "DW_FORM_strx,strx1..4", "supported",
         "resolves via .debug_str_offsets with contribution bounds"},
        {"forms", "DW_FORM_addrx,addrx1..4", "supported",
         "resolves via .debug_addr with bounded contribution reads"},
        {"forms", "DW_FORM_GNU_str_index/DW_FORM_GNU_addr_index", "supported",
         "GNU indexed predecessors parsed as strx/addrx aliases"},
        {"forms", "DW_FORM_loclistx", "supported",
         "DWARF v5 indexed location lists"},
        {"forms", "DW_FORM_rnglistx", "supported",
         "DWARF v5 indexed range lists"},
        {"forms", "DW_FORM_line_strp", "supported",
         "line string table lookups"},
        {"forms", "DW_FORM_strp_sup", "supported",
         "supplementary string section lookups"},
        {"forms", "DW_FORM_ref_sup4/ref_sup8", "supported",
         "supplementary references with bias"},
        {"forms", "DW_FORM_GNU_strp_alt/DW_FORM_GNU_ref_alt", "supported",
         "GNU alternate forms parsed with supplementary string/reference semantics"},
        {"forms", "DW_FORM_data16", "supported",
         "parsed as 16-byte block"},
        {"forms", "DW_FORM_implicit_const", "supported",
         "abbrev SLEB128 propagated as signed attribute value"},
        {"expr", "core stack/arithmetic/compare", "supported",
         "includes lit/reg/breg ranges, branch ops, and utility string round-trip mapping"},
        {"expr", "typed ops (*_type/convert/reinterpret)", "supported",
         "includes GNU predecessor opcodes"},
        {"expr", "indexed ops (DW_OP_addrx/DW_OP_constx)", "supported",
         "includes GNU *_index variants plus utility round-trip and operand-size decoding"},
        {"expr", "piecewise ops (piece/bit_piece)", "supported",
         "composite locations with implicit/unavailable pieces"},
        {"expr", "TLS ops", "supported",
         "DW_OP_form_tls_address and GNU equivalent"},
        {"expr", "entry/call ops", "supported",
         "entry_value/call2/call4/call_ref, including entry_value materialization of register/address subexpressions to entry-time values"},
        {"expr", "WebAssembly extension (DW_OP_WASM_location)", "supported",
         "tokenization includes kind/index annotations; concrete and symbolic evaluators preserve synthetic WASM register-location identifiers"},
        {"expr", "GNU extensions", "supported",
         "the enumerated GNU DW_OP_* predecessor set is implemented in utility decoding plus concrete and symbolic evaluators, including TLS, entry/value, typed, implicit-pointer, parameter-ref, encoded_addr, and *_index variants"},
        {"expr", "unknown vendor/extension opcodes", "unsupported",
         "opcodes outside the known GNU set remain rejected by design while preserving unsupported_opcode and unsupported_vendor_extension diagnostics"},
        {"analysis", "SMT symbolic unknown-leaf handling", "supported",
         "symbolic unknown(...) leaves are encoded as opaque solver variables instead of immediate encoding failures"},
        {"analysis", "SMT uninitialized-taint equivalence", "supported",
         "verification rejects matches where value expressions agree but uninitialized taint differs"},
        {"analysis", "SMT wide-byte literal prechecks", "supported",
         "top-level BYTES literals wider than 64 bits compare deterministically instead of causing encoding_error"},
        {"analysis", "SMT composite wide-byte piece prechecks", "supported",
         "composite piece locations carrying wide BYTES expressions compare deterministically instead of causing encoding_error"},
        {"analysis", "SMT structural equality prechecks", "supported",
         "exact symbolic-expression matches short-circuit before SMT, including unsupported shapes such as identical load(...,9) terms"},
        {"analysis", "SMT malformed symbolic-shape prechecks", "supported",
         "malformed/internal symbolic shapes with invalid arity now short-circuit deterministically instead of surfacing as generic encoding_error"},
        {"analysis", "SMT invalid load/kind prechecks", "supported",
         "zero-byte loads and invalid symbolic kind discriminants now short-circuit deterministically instead of surfacing as generic encoding_error"},
        {"analysis", "SMT oversized-load abstraction", "supported",
         "LOAD terms wider than 64 bits are modeled as opaque solver-visible values instead of immediate encoding failures"},
        {"analysis", "SMT encoding_error elimination", "supported",
         "symbolic-expression content no longer reports encoding_error; residual failures are backend/implementation defects rather than DWARF-shape limitations"},
        {"semantic", "preserved call-site/discriminant payload decoding", "supported",
         "utility helpers expose structured decoding for DW_AT_call_value/DW_AT_call_parameter/DW_AT_discr_list, including raw bytes, expression tokens, assembly rendering, and dwarf_dump surfacing"},
        {"semantic", "DW_AT_trampoline/DW_AT_extension", "supported",
         "standard relationship attributes now decode through the explicit reference-metadata path and surface as ordinary DIE references"},
        {"split-dwarf", ".dwo discovery/loading", "supported",
         "skeleton attributes drive DWO loading, including real compiler-produced relocatable split-DWARF fixtures"},
        {"split-dwarf", ".dwp index parsing", "supported",
         "CU/TU index parsing with bounded section extraction, including packaged real-DWO payload coverage"},
        {"split-dwarf", "DWO debug_addr in expr eval", "supported",
         "indexed ops resolve against .debug_addr.dwo when available"},
        {"split-dwarf", "unknown DWP section ids", "supported",
         "unknown sections are skipped safely and surfaced through parser/runtime telemetry"}
    };
    return kRows;
}

} // namespace dwarf
